name: Update counter

on:
  schedule:
    - cron: '7 23 * * *'

permissions:
  contents: write

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update the counter
        run: |
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
