name: Update analysis

on:
  schedule:
    - cron: '7 23 * * *'

permissions:
  contents: write

jobs:
  update-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update the analysis
        run: |
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
          ./update_analysis.sh
