name: Update counter

on:
  schedule:
    - cron: '* * * * *'

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Update the counter
        run: |
          ./update_counter.sh
          ./update_counter.sh
          ./update_counter.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
